spring.datasource.url=jdbc:postgresql://localhost:5432/devaihub
spring.datasource.username=postgres
spring.datasource.password=Aarti@8737

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081