spring.application.name=backend

# ==========================
# DATABASE CONFIGURATION
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/devaihub
spring.datasource.username=postgres
spring.datasource.password=Aarti@8737

# ==========================
# JPA CONFIGURATION
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# SERVER CONFIGURATION
# ==========================
server.port=8081

# ================= JWT =================
jwt.secret=ThisIsASecretKeyForDevAIHubProjectManagementSystem2026SpringBootJWT
jwt.expiration=86400000
